apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: "{{ .Values.vault.postgresRole }}"
        vault.hashicorp.com/agent-inject-secret-postgres-user: "{{ .Values.vault.secretPath }}"
        vault.hashicorp.com/agent-inject-template-postgres-user: |
          {{ "{{-" }} with secret "{{ .Values.vault.secretPath }}" {{ "-}}" }}{{ "{{-" }} .Data.data.POSTGRES_USER {{ "-}}" }}{{ "{{-" }} end {{ "-}}" }}
        vault.hashicorp.com/agent-inject-secret-postgres-password: "{{ .Values.vault.secretPath }}"
        vault.hashicorp.com/agent-inject-template-postgres-password: |
          {{ "{{-" }} with secret "{{ .Values.vault.secretPath }}" {{ "-}}" }}{{ "{{-" }} .Data.data.POSTGRES_PASSWORD {{ "-}}" }}{{ "{{-" }} end {{ "-}}" }}
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: postgres
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: {{ .Values.postgres.containerPort }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          env:
            - name: POSTGRES_USER_FILE
              value: /vault/secrets/postgres-user
            - name: POSTGRES_PASSWORD_FILE
              value: /vault/secrets/postgres-password
            - name: POSTGRES_DB
              value: {{ .Values.postgres.dbName | quote }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "aegis"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "aegis"]
            initialDelaySeconds: 15
            periodSeconds: 20
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgres.storageSize }}