apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dcgm-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://nvidia.github.io/dcgm-exporter/helm-charts
    chart: dcgm-exporter
    targetRevision: "*"
    helm:
      releaseName: dcgm-exporter
      valuesObject:
        nodeSelector:
          nvidia.com/gpu.present: "true"
        runtimeClassName: nvidia
        serviceMonitor:
          enabled: true
          additionalLabels:
            release: kube-prometheus-stack
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true