apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rag-eval
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/amirhosssein0/ai-platform-lab.git
    targetRevision: develop
    path: k8s/eval
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true