apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llm-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/amirhosssein0/ai-platform-lab.git
    targetRevision: develop
    path: k8s/llm-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: llm-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true